;; autocad-ballet
(defun c:q` () (command "invoke-addin-command"))
(defun c:qq` () (command "invoke-last-addin-command"))
(defun c:ww () (command "switch-view"))
(defun c:wwl () (command "switch-layout"))
(defun c:wwd () (command "switch-document"))
(defun c:we () (command "switch-view-last"))
(defun c:wr () (command "switch-view-recent"))
(defun c:fse () (command "filter-selection-elements"))
(defun c:fses () (command "filter-selection-elements-span"))
(defun c:scv () (command "select-by-categories-in-view"))
(defun c:scd () (command "select-by-categories-in-document"))
(defun c:sca () (command "select-by-categories-in-application"))
(defun c:slv () (command "select-by-layers-in-view"))
(defun c:sld () (command "select-by-layers-in-document"))
(defun c:sla () (command "select-by-layers-in-application"))
(defun c:fv () (command "filter-selection-in-view"))
(defun c:fd () (command "filter-selection-in-document"))
(defun c:fa () (command "filter-selection-in-application"))
(defun c:ssl () (command "select-entities-on-same-layer"))
(defun c:or () (command "open-documents-recent"))
(defun c:orr () (command "open-documents-recent-read-only"))
(defun c:etv () (command "edit-selected-text-in-view"))
(defun c:eta () (command "edit-selected-text-in-application"))
(defun c:zs () (c:zoom-selected))
(defun c:saf () (c:save-all-force))

;; regular autocad
(defun c:fs () (command "refclose" "save"))
(defun c:rs () (command "refset"))
(defun c:rsa () (command "refset" "add"))
(defun c:rsr () (command "refset" "remove"))
(defun c:rf () (command "-refedit" "ok" "all" "no"))
(defun c:sv () (command ".selectsimilar"))
(defun c:pii () (command "pickstyle"))
(defun c:cc () (command "lay-cur"))
(defun c:chh () (command "change-color"))
(defun c:ze () (command "zoom" "extents"))
(defun c:cbb () (command "copybase" "0,0,0"))
(defun c:ccb () (command "cutbase" "0,0,0"))
(defun c:cbb () (command "copybase" "0,0,0"))
(defun c:pbb () (command "pasteclip" "0,0,0"))
(defun c:hh () (command "hideobjects"))
(defun c:ii () (command "isolate-objects"))
(defun c:jj () (command "lay-mcur-make-object-layer-current"))
(defun c:uu () (command "unisolateobjects"))
(defun c:dps () (command "toggle-display-plot-styles"))
(defun c:ss () (command "_.pselect" "_p" "")(princ))
(defun c:ssc () (sssetfirst nil (ssget "x" (list (cons 8 (getvar "clayer")))))(princ))
(defun c:sbc () (command "select-by-color"))
(defun c:bf () (command "draworder" "front"))
(defun c:sb () (command "draworder" "back"))
;; needed until i find out why ctrl+double click no longer edits block attributes in-place
(defun c:at () (command "attipedit"))
(defun c:fr () (command "layfrz"))
(defun c:tg () (setvar "pickstyle" (- 1 (getvar "pickstyle"))))
(defun c:tv () (command "-vports" "toggle"))
