;; add (princ) to properly cleanup command and avoid context leaks in application-level commands
;; autocad-ballet
(defun c:q` () (command "invoke-addin-command") (princ))
(defun c:qq` () (command "invoke-last-addin-command") (princ))
(defun c:ww () (command "switch-view") (princ))
(defun c:wwl () (command "switch-layout") (princ))
(defun c:wwd () (command "switch-document") (princ))
(defun c:we () (command "switch-view-last") (princ))
(defun c:wr () (command "switch-view-recent") (princ))
(defun c:fse () (command "filter-selection-elements") (princ))
(defun c:fses () (command "filter-selection-elements-span") (princ))
(defun c:scv () (command "select-by-categories-in-view") (princ))
(defun c:scd () (command "select-by-categories-in-document") (princ))
(defun c:sca () (command "select-by-categories-in-application") (princ))
(defun c:slv () (command "select-by-layers-in-view") (princ))
(defun c:sld () (command "select-by-layers-in-document") (princ))
(defun c:sla () (command "select-by-layers-in-application") (princ))
(defun c:fv () (command "filter-selection-in-view") (princ))
(defun c:fd () (command "filter-selection-in-document") (princ))
(defun c:fa () (command "filter-selection-in-application") (princ))
(defun c:slv () (command "select-similar-by-layer-in-view") (princ))
(defun c:or () (command "open-documents-recent") (princ))
(defun c:orr () (command "open-documents-recent-read-only") (princ))
(defun c:et () (command "edit-selected-text-in-view") (princ))
(defun c:etv () (command "edit-selected-text-in-view") (princ))
(defun c:eta () (command "edit-selected-text-in-application") (princ))
(defun c:zs () (c:zoom-selected))
(defun c:saf () (c:save-all-force))
(defun c:wc () (command "close" "y") (princ))
(defun c:wcc () (c:close-all-without-saving))

;; regular autocad
(defun c:fs () (command "refclose" "save") (princ))
(defun c:rs () (command "refset") (princ))
(defun c:rsa () (command "refset" "add") (princ))
(defun c:rsr () (command "refset" "remove") (princ))
(defun c:rf () (command "-refedit" "ok" "all" "no") (princ))
(defun c:sv () (command ".selectsimilar") (princ))
(defun c:pii () (command "pickstyle") (princ))
(defun c:cc () (command "lay-cur") (princ))
(defun c:chh () (command "change-color") (princ))
(defun c:ze () (command "zoom" "extents") (princ))
(defun c:cbb () (command "copybase" "0,0,0") (princ))
(defun c:ccb () (command "cutbase" "0,0,0") (princ))
(defun c:cbb () (command "copybase" "0,0,0") (princ))
(defun c:pbb () (command "pasteclip" "0,0,0") (princ))
(defun c:hh () (command "hideobjects") (princ))
(defun c:ii () (command "isolate-objects") (princ))
(defun c:jj () (command "lay-mcur-make-object-layer-current") (princ))
(defun c:uu () (command "unisolateobjects") (princ))
(defun c:dps () (command "toggle-display-plot-styles") (princ))
(defun c:ss () (command "_.pselect" "_p" "") (princ))
(defun c:ssc () (sssetfirst nil (ssget "x" (list (cons 8 (getvar "clayer"))))) (princ))
(defun c:sbc () (command "select-by-color") (princ))
(defun c:bf () (command "draworder" "front") (princ))
(defun c:sb () (command "draworder" "back") (princ))
;; needed until i find out why ctrl+double click no longer edits block attributes in-place
(defun c:at () (command "attipedit") (princ))
(defun c:fr () (command "layfrz") (princ))
(defun c:tg () (setvar "pickstyle" (- 1 (getvar "pickstyle"))) (princ))
(defun c:tv () (command "-vports" "toggle") (princ))
